# Form implementation generated from reading ui file 'D:\Project_KTLT\code\MainWindow_Statics.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 131, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Home = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Home.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Home.setObjectName("Home")
        self.verticalLayout.addWidget(self.Home)
        self.Statics = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Statics.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(255, 0, 0);")
        self.Statics.setObjectName("Statics")
        self.verticalLayout.addWidget(self.Statics)
        self.Movie_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Movie_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"")
        self.Movie_2.setObjectName("Movie_2")
        self.verticalLayout.addWidget(self.Movie_2)
        self.Theater = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Theater.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Theater.setObjectName("Theater")
        self.verticalLayout.addWidget(self.Theater)
        self.Schedule = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Schedule.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Schedule.setObjectName("Schedule")
        self.verticalLayout.addWidget(self.Schedule)
        self.Staff = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Staff.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Staff.setObjectName("Staff")
        self.verticalLayout.addWidget(self.Staff)
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 1001, 61))
        self.label_9.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(255, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 141, 61))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("D:\\Project_KTLT\\code\\../images/logo.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.Back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(10, 665, 119, 31))
        self.Back.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);")
        self.Back.setObjectName("Back")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 80, 751, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Project_KTLT\\code\\../images/dashboard.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Home.setText(_translate("MainWindow", "TRANG CHỦ"))
        self.Statics.setText(_translate("MainWindow", "THỐNG KÊ"))
        self.Movie_2.setText(_translate("MainWindow", "PHIM"))
        self.Theater.setText(_translate("MainWindow", "RẠP"))
        self.Schedule.setText(_translate("MainWindow", "SUẤT CHIẾU"))
        self.Staff.setText(_translate("MainWindow", "NHÂN SỰ"))
        self.label_9.setText(_translate("MainWindow", "THỐNG KÊ"))
        self.Back.setText(_translate("MainWindow", "Quay lại"))
