# Form implementation generated from reading ui file 'D:\Project_KTLT\code\MainWindow_Movie_1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 131, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Home = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Home.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Home.setObjectName("Home")
        self.verticalLayout.addWidget(self.Home)
        self.Statics = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Statics.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Statics.setObjectName("Statics")
        self.verticalLayout.addWidget(self.Statics)
        self.Movie_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Movie_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(255, 0, 0);")
        self.Movie_2.setObjectName("Movie_2")
        self.verticalLayout.addWidget(self.Movie_2)
        self.Theater = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Theater.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Theater.setObjectName("Theater")
        self.verticalLayout.addWidget(self.Theater)
        self.Schedule = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Schedule.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Schedule.setObjectName("Schedule")
        self.verticalLayout.addWidget(self.Schedule)
        self.Staff = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Staff.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Staff.setObjectName("Staff")
        self.verticalLayout.addWidget(self.Staff)
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 1001, 51))
        self.label_9.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(255, 0, 0);\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 131, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("D:\\Project_KTLT\\code\\../images/logo.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 131, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.List = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.List.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(255, 0, 0);")
        self.List.setObjectName("List")
        self.verticalLayout_2.addWidget(self.List)
        self.Update = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.Update.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.Update.setObjectName("Update")
        self.verticalLayout_2.addWidget(self.Update)
        self.Back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(10, 655, 119, 31))
        self.Back.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);")
        self.Back.setObjectName("Back")
        self.Tab = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.Tab.setGeometry(QtCore.QRect(160, 80, 811, 611))
        self.Tab.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Tab.setColumnCount(6)
        self.Tab.setObjectName("Tab")
        self.Tab.setRowCount(0)
        self.Tab.horizontalHeader().setDefaultSectionSize(130)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Home.setText(_translate("MainWindow", "TRANG CHỦ"))
        self.Statics.setText(_translate("MainWindow", "THỐNG KÊ"))
        self.Movie_2.setText(_translate("MainWindow", "PHIM"))
        self.Theater.setText(_translate("MainWindow", "RẠP"))
        self.Schedule.setText(_translate("MainWindow", "SUẤT CHIẾU"))
        self.Staff.setText(_translate("MainWindow", "NHÂN SỰ"))
        self.label_9.setText(_translate("MainWindow", "PHIM"))
        self.List.setText(_translate("MainWindow", "DANH SÁCH"))
        self.Update.setText(_translate("MainWindow", "CẬP NHẬT"))
        self.Back.setText(_translate("MainWindow", "Quay lại"))
